### ISSUE TITLE
Image Variants are private , Where as original image is public

### ISSUE THREAD

**Issue by ravdeepsingh22** [plank/laravel-mediable#270]
The generated variants are saved privately in S3 .
Have explicitly specified the original image to be public , while uploading

**Comment by frasmage** [comment]
Fixed in 5.3.1

**Comment by ubxty** [comment]
@frasmage This issue still persists .
Here is a code snippet

`  
        $media = MediaUploader::fromString($image)
                ->makePublic()
                ->toDestination('s3', $directory)
                ->onDuplicateIncrement()
                ->useFilename(generate_unique_name())
                ->beforeSave(function ($model) use ($request, $key) {
                    $model->original_filename = $request->file($key)->getClientOriginalName();
                    $model->uuid = Str::uuid();
                })
                ->upload();
        }
  
        CreateImageVariants::dispatch($media, [FileVarientConstants::FILE_VARIENT_SMALL, FileVarientConstants::FILE_VARIENT_MEDIUM, FileVarientConstants::FILE_VARIENT_LARGE]);
      
    `

This creates 4 files in S3 (Digital ocean spaces) , The original file is public , but the other files are private

![image](https://user-images.githubusercontent.com/48719351/159862061-e1f55787-6aeb-42fe-b73f-662408d7ea9c.png)
The top 3 files are private .

Are there any specific params required to be passed into the job ?

**Comment by ls-sean-fraser** [comment]
Variants will use the default visibility of the disk unless you specify otherwise. You can use the following on the ImageManipulation definition to override that behaviour.

```php
$manipulation->makePrivate();
$manipulation->makePublic();
$manipulation->matchOriginalVisibility();
```

**Comment by ubxty** [comment]
I have defined the manipulation in AppServiceProvider as below 

Where to apply `$manipulation->makePublic();`

```

public function boot()    {
....
ImageManipulator::defineVariant(
            FileVarientConstants::FILE_VARIENT_MEDIUM,
            ImageManipulation::make(function (Image $image) {
                $image->resize(256, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
            })
        );
....
}
```

**Comment by ubxty** [comment]
@ls-sean-fraser

**Comment by ls-sean-fraser** [comment]
`ImageManipulation::make(...)->makePublic();`

**Comment by frasmage** [comment]
Append to the make call

`ImageManipulation::make(...)->makePublic()`
