### ISSUE TITLE
Can not upgrade to new version, I've read all upgrade guides

### ISSUE THREAD

**Issue by siarheipashkevich** [plank/laravel-mediable#350]
<img width="1381" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/7371a3d3-41a8-47e3-bb5f-d09dbafda2e3">

<img width="671" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/4622d58e-1373-4a32-b67f-15df9947700a">

**Comment by frasmage** [comment]
The step you are missing is in the upgrade guides and documentation

> (optional) If upgrading the intervention/image package to 3.X, be sure to review the [upgrading instructions](https://image.intervention.io/v3/introduction/upgrade) for that package. Notably, the Laravel service providers for configuring the package have been moved to a separate repository [intervention/image-laravel](https://github.com/Intervention/image-laravel)

https://laravel-mediable.readthedocs.io/en/latest/variants.html#configure-intervention-image-imagemanager

**Comment by siarheipashkevich** [comment]
By this documentation https://laravel-mediable.readthedocs.io/en/latest/variants.html#configure-intervention-image-imagemanager I have two choices:
1) install [intervention/image-laravel](https://image.intervention.io/v3/introduction/frameworks#laravel) package
OR
2) manually bind to the service container needed interfaces as described in you documentation

I prefer 1 option. But!! I can't install this package, when I'm trying to require this package I'm getting an error which I posted in the issu.

**Comment by siarheipashkevich** [comment]
1) upgrade laravel-mediable to the latest version
2) try to upgrade intervention/image to the latest version, but getting an error
<img width="1979" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/7a3936c0-750b-4858-b31c-cab9d668dee0">

**Comment by frasmage** [comment]
ok, I see the problem. A bit of a chicken and egg situation in package discovery. Will change it to create a null driver.

**Comment by frasmage** [comment]
Released 6.1.0 which will attempt to automatically pick a driver while still allowing it to be configured using intervention/image-laravel.

**Comment by siarheipashkevich** [comment]
```
[2024-04-09 16:22:02] staging.ERROR: Intervention\Image\ImageManager::__construct(): Argument #1 ($driver) must be of type Intervention\Image\Interfaces\DriverInterface|string, array given, called in /home/forge/api.stage...com/vendor/plank/laravel-mediable/src/MediableServiceProvider.php on line 245 {"exception":"[object] (TypeError(code: 0): Intervention\\Image\\ImageManager::__construct(): Argument #1 ($driver) must be of type Intervention\\Image\\Interfaces\\DriverInterface|string, array given, called in /home/forge/api.stage...com/vendor/plank/laravel-mediable/src/MediableServiceProvider.php on line 245 at /home/forge/api.stage...com/vendor/intervention/image/src/ImageManager.php:22)
[stacktrace]
#0 /home/forge/api.stage...com/vendor/plank/laravel-mediable/src/MediableServiceProvider.php(245): Intervention\\Image\\ImageManager->__construct()
#1 /home/forge/api.stage...com/vendor/plank/laravel-mediable/src/MediableServiceProvider.php(194): Plank\\Mediable\\MediableServiceProvider->getInterventionImageManagerConfiguration()
#2 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Plank\\Mediable\\MediableServiceProvider->Plank\\Mediable\\{closure}()
#3 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#4 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#5 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#6 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#7 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()
#8 /home/forge/api.stage...com/vendor/plank/laravel-mediable/src/MediableServiceProvider.php(152): Illuminate\\Container\\Container->offsetGet()
#9 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Plank\\Mediable\\MediableServiceProvider->Plank\\Mediable\\{closure}()
#10 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#11 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#12 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#13 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#14 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#15 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#16 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#17 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#18 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#19 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#20 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#21 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Console/Application.php(251): Illuminate\\Foundation\\Application->make()
#22 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Console/Application.php(265): Illuminate\\Console\\Application->resolve()
#23 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(404): Illuminate\\Console\\Application->resolveCommands()
#24 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Console/Application.php(130): Illuminate\\Support\\ServiceProvider->Illuminate\\Support\\{closure}()
#25 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Console/Application.php(77): Illuminate\\Console\\Application->bootstrap()
#26 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(481): Illuminate\\Console\\Application->__construct()
#27 /home/forge/api.stage...com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Illuminate\\Foundation\\Console\\Kernel->getArtisan()
#28 /home/forge/api.stage...com/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#29 {main}
"} 
```

**Comment by siarheipashkevich** [comment]
@frasmage please reopen this issue

**Comment by siarheipashkevich** [comment]
I've updated to the latest versions for all packages, but in the stage my deploy is failed
<img width="644" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/9e83984d-7ad3-4104-bd4d-56056143d18b">

**Comment by siarheipashkevich** [comment]
There is my deployment script:
<img width="745" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/bc7b2375-b182-4158-8cb8-00dd13f0d3e6">

**Comment by frasmage** [comment]
found it, typo in the class name `GD` vs. `Gd`, which didn't fail when I tested it on a case-insensitive drive.

Addressed in 6.1.1

**Comment by siarheipashkevich** [comment]
Thanks a lot. I will update soon

**Comment by siarheipashkevich** [comment]
@frasmage it is not fixed (

<img width="757" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/55578e27-d727-42bd-a729-7f3c7e182191">

**Comment by frasmage** [comment]
Are you sure that you have version 6.1.1? I am recreated an environment with the same versions you listed above and am no longer able to reproduce the issue.

The screenshot above indicated that your lock file might not be aligned with your composer.json (`^6.1` required vs `6.0.3` actual). Be sure to run `composer update plank/laravel-mediable` before committing and deploying

**Comment by siarheipashkevich** [comment]
@frasmage yes, sorry. This issue happened after the first failed deployment (where the version has typo), therefore when I update the version and pushed to the remote repository I try to deploy one more time. If you see my deployment script where I have some instructions for clearing cache and something else and only after that I'm installing packages.

Thanks for your helping!
